return 'CHECKING FOR SNOMED_G_UPDATE_FAILURE NODE WHICH INDICATES FAILURE';

match (a:SNOMED_G_UPDATE_FAILURE)
LOAD CSV with headers from "UPDATE FAILURE DETECTED" as line create (b:UPDATE_FAILED)
return 'SNOMED_G GRAPH UPDATE SUCCEEDED';
