#!/bin/bash
prog=`basename "$self"`
mysqlrun='mysql'
mysqlload='mysql_load'
mode="standard"
cnfname="my_snomedimport_client"
portnumber=3306
mysqluser=root
sqlsource="sct_mysql_load_VP_latest"
sqltarget="sct_mysql_load_VP_views"
sql_src="$EPSDRIVE/SnomedRfs/SnomedRfsMySql/$mysqlload/$sqlsource.sql"
sql_tgt="$EPSDRIVE/SnomedRfs/SnomedRfsMySql/$mysqlload/$sqltarget.sql"
cnf_file="$EPSDRIVE/SnomedRfs/SnomedRfsMySql/cnf/${cnfname}.cnf"

awk '/^-- START VIEWS --/{start=1};/^-- START EXTRAS --/{start=1};/^-- END VIEWS --/{start=0};/^-- END EXTRAS --/{start=0};{if (start==1) print $0}' "$sql_src" >"$sql_tgt"

snomed_load_mysql -c my_snomedimport_client -p 3306 -s VP_views -r /Users/dma/SnomedCT_ReleaseFiles/SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z -mode skiptc
